// Generated by CoffeeScript 1.3.1
var Post;

Post = Jewel.define('div.posts', {
  keys: {
    title: 'h1',
    body: 'p'
  },
  template: function(fields) {
    return "<div class=\"post\"><h1>" + fields.title + "</h1><p>" + fields.body + "</p></div>";
  }
});

describe('Jewel', function() {
  it('should fetch all posts', function() {
    return expect(Post.all.length).to.be(2);
  });
  it('should fetch first post', function() {
    return expect(Post.find({
      limit: 1
    })[0].title).to.be('First post');
  });
  it('should fetch second post', function() {
    return expect(Post.find({
      skip: 1
    })[0].title).to.be('Second post');
  });
  it('should create new post', function() {
    var post;
    post = new Post;
    post.title = 'Third post';
    post.body = 'Third content';
    post.save();
    return expect(Post.find({
      limit: 1
    })[0].title).to.be('Third post');
  });
  it('should update third post', function() {
    var post;
    post = Post.find({
      limit: 1
    })[0];
    post.title = 'Latest post';
    post.save();
    return expect(Post.find({
      limit: 1
    })[0].title).to.be('Latest post');
  });
  it('should remove second post', function() {
    Post.find({
      skip: 1
    })[0].remove();
    return expect(Post.all.length).to.be(2);
  });
  return it('should remove all posts', function() {
    Post.remove();
    return expect(Post.all.length).to.be(0);
  });
});
